const ROLES = Object.freeze({
  SUPER_ADMIN:     'SUPER_ADMIN',
  SCHOOL_ADMIN:    'SCHOOL_ADMIN',
  CAMPUS_ADMIN:    'CAMPUS_ADMIN',
  PRINCIPAL:       'PRINCIPAL',
  TEACHER:         'TEACHER',
  EXAM_CONTROLLER: 'EXAM_CONTROLLER',
  ACCOUNTANT:      'ACCOUNTANT',
  RECEPTIONIST:    'RECEPTIONIST',
  GUARDIAN:        'GUARDIAN',
  STUDENT:         'STUDENT',
})

export default ROLES
